// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
          apiKey: '', appId: '', messagingSenderId: '', projectId: '');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAkf3CJf_KDapHnHwSDTd0FlDBal2alaDc",
      authDomain: "aiweglobal.firebaseapp.com",
      projectId: "aiweglobal",
      storageBucket: "aiweglobal.appspot.com",
      messagingSenderId: "879472760468",
      appId: "1:879472760468:web:ab83ae3ea4df834faa0681",
      measurementId: "G-FML3QDSHMW");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxvc8247bXy1WrIl9jz1XQZoQBJaB2MsU',
    appId: '1:879472760468:ios:01a7e517bace10e6aa0681',
    messagingSenderId: '441036325327',
    projectId: 'aiweglobal',
    storageBucket: "aiweglobal.appspot.com",
    iosBundleId: 'ai.weglobal.mobile',
  );
}
